# Generated by Django 3.2.15 on 2022-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('es', 'Italian'), ('kk', 'Kazakh'), ('zh', 'Chinese'), ('de', 'Deutsch')], default='en', max_length=2),
        ),
    ]
