# Generated by Django 4.1.1 on 2022-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options_bookinstance_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('es', 'Italian'), ('kk', 'Kazakh'), ('zh', 'Chinese'), ('de', 'Deutsch')], default='en', max_length=2),
        ),
    ]
